### PR TITLE
Initial UI and Beginning of FSM

### LINKED ISSUE #10: Travis not failing when it should
This is likely due to the code coverage step passing, despite tests failing.

### PR DESCRIPTION
**Pull request by kuzi117**
So this PR is sort of muddling two issues together but not completing either.

#1: There are the beginning of hooks in the callback functions to update game state. Figured it would be better to commit this back quickly.
#2: This renders game tiles (does not reflect board state yet) but not the movements, so there's no ability to choose the action to take.

tl;dr:
Progress towards #1.
Progress towards #2.
Closes #10.

### CODE REVIEW

**Comment by kuzi117** [comment]
@knewbury01: The idea here is that gameboard should implement `CallbackConsumer` and certain methods will be called to update the FSM in the gameboard.

**Comment by kuzi117** [comment]
As well, this also absolutely destroys code coverage because of the Renderer being slightly untestable. We might have to look into how to mock UI stuff if we want to hit 99%.

File: src/test/java/SquareClickCallbackTest.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import org.junit.Test;
+import static junit.framework.TestCase.assertEquals;
+import static junit.framework.TestCase.assertTrue;
+
+import java.awt.Point;
+import java.awt.event.ActionEvent;
+
+public class SquareClickCallbackTest {
+
+    CallbackConsumerMock cb;
```
Comment (knewbury01) [inline src/test/java/SquareClickCallbackTest.java:14]: will this be refactored to meet the assignment specification of using mock instead of stub? 
[pg 4](https://eclass.srv.ualberta.ca/pluginfile.php/4748721/mod_resource/content/5/CMPUT402_501_Assignment4.pdf)
"You need to use a mocking framework (e.g.,
mockito for Java)" 
this is currently stub technically , as per [slide 17](https://github.com/cmput402-w19/lab-content/blob/master/lab-lectures/week-2/slides.pdf)

File: .travis.yml [hunk 2]
```diff
@@ -1,6 +1,7 @@
 language: java
 
-script: "mvn cobertura:cobertura"
+script: mvn test
```
Comment (knewbury01) [inline .travis.yml:3]: Thank you! if this was the fix its beautiful and simple, and yet I totally could not figure that out

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java [hunk 3]
```diff
@@ -1,5 +1,44 @@
...
+
+    private static class GUIThread implements Runnable {
+        @Override
+        public void run() {
+            // TODO: Clean up when pulling in board changes.
+            Board board = new Board();
+
+            // Create renderer.
+            // TODO: Use actual board dimensions for width/height
+            SwingRenderer renderer = new SwingRenderer(new Dimension(5, 5));
```
Comment (knewbury01) [inline src/main/java/cs/ualberta/cmput402/boardgame/Game.java:23]: containing a TODO, can we replace the 5s yet with a call to board to get its size?

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java [hunk 4]
```diff
@@ -1,5 +1,44 @@
...
+import cs.ualberta.cmput402.boardgame.rendering.SwingRenderer;
 
+import javax.swing.*;
+import java.awt.*;
+
+public class Game {
+
+    public static void main(String[] args) {
+        SwingUtilities.invokeLater(new GUIThread());
+        System.out.println("Hello");
```
Comment (knewbury01) [inline src/main/java/cs/ualberta/cmput402/boardgame/Game.java]: Should remove this for the pr

File: src/main/java/cs/ualberta/cmput402/boardgame/rendering/GameRenderer.java [hunk 5]
```diff
@@ -0,0 +1,12 @@
+package cs.ualberta.cmput402.boardgame.rendering;
+
+import cs.ualberta.cmput402.boardgame.board.Board;
+
+public interface GameRenderer {
```
Comment (knewbury01) [inline src/main/java/cs/ualberta/cmput402/boardgame/rendering/GameRenderer.java:5]: interesting choice, I dont see why this interface exists, can you explain that design choice?

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java (hunk 3 above)
Comment (knewbury01) [reply src/main/java/cs/ualberta/cmput402/boardgame/Game.java:23]: actually I can see if you want to leave that to the next pr to get all of those types of changes grouped together

File: src/test/java/SquareClickCallbackTest.java (hunk 1 above)
Comment (knewbury01) [reply src/test/java/SquareClickCallbackTest.java:14]: actually though. also maybe this can wait to see how mocking goes in renderer.

**Comment by knewbury01** [comment]
Oh one last thing, I think that [#1](https://github.com/cmput402-w19/assignment4tdd-goodteam/issues/1) needs to stay unique to the board ability

I will open another issue to better describe the ability of the renderer to update the board with callbacks, but that will rely upon [#1](https://github.com/cmput402-w19/assignment4tdd-goodteam/issues/1), but not be the same feature

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java (hunk 3 above)
Comment (kuzi117) [reply src/main/java/cs/ualberta/cmput402/boardgame/Game.java:23]: Yeah, that's the integration I need to do yet. I wanted to send this off to you so that you could see how I wanted to interact with the game. We need to add more interactions in the callback consumer, once for each fsm transition or something.

File: src/main/java/cs/ualberta/cmput402/boardgame/rendering/GameRenderer.java (hunk 5 above)
Comment (kuzi117) [reply src/main/java/cs/ualberta/cmput402/boardgame/rendering/GameRenderer.java:5]: An example of TDD not gone quite right. The idea was that I could mock a renderer like callback consumer to fake UI for testing but I can't see far enough into the future to properly abstract the UI away from the game.

**Comment by kuzi117** [comment]
I'm not sure what you mean "unique to the board ability" if not callbacks?

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java (hunk 4 above)
Comment (kuzi117) [reply src/main/java/cs/ualberta/cmput402/boardgame/Game.java]: ....You're definitely right.

File: .travis.yml (hunk 2 above)
Comment (kuzi117) [reply .travis.yml:3]: It seems to work from my testing, but I have no idea if this is all it needs.

File: src/test/java/SquareClickCallbackTest.java (hunk 1 above)
Comment (kuzi117) [reply src/test/java/SquareClickCallbackTest.java:14]: I can't tell if this is a stub or mock because it _is_ checking if we're using the "service". I should look into Mockito here.

File: src/main/java/cs/ualberta/cmput402/boardgame/Game.java (hunk 4 above)
Comment (kuzi117) [reply src/main/java/cs/ualberta/cmput402/boardgame/Game.java]: Fixed 7bc6aadea9753f1e39d0cc34c2cd9d0e98642799.

File: src/test/java/SquareClickCallbackTest.java (hunk 1 above)
Comment (knewbury01) [reply src/test/java/SquareClickCallbackTest.java:14]: will look into it with next pr, can be left to refactor
